eclipse-zenoh-flow/zenoh-flow

zenoh-flow-examples/examples/video-pipeline.rs
zenoh-flow-examples/graphs/car-pipeline-multi-runtime.yaml
zenoh-flow-examples/graphs/dnn-object-detection-multi-runtime.yaml
zenoh-flow-examples/graphs/dnn-object-detection.yaml
zenoh-flow-examples/graphs/face-detection-multi-runtime.yaml
zenoh-flow-examples/graphs/face_detection.yaml
zenoh-flow-examples/graphs/fizz-buzz-multiple-runtimes.yaml
zenoh-flow-examples/graphs/fizz_buzz_pipeline.yaml
zenoh-flow-examples/graphs/random_source.yaml
zenoh-flow-examples/graphs/simple_pipeline.yaml
zenoh-flow-examples/graphs/stereo-car-camera-pipeline.yaml
zenoh-flow-examples/graphs/video_pipeline.yaml
zenoh-flow-examples/graphs/zface_detection.yaml
zenoh-flow-examples/graphs/zvideo_pipeline.yaml
zenoh-flow/src/model/dataflow.rs
zenoh-flow/src/model/link.rs
zenoh-flow/src/runtime/graph/mod.rs
zenoh-flow/src/runtime/message.rs

The new syntax to declare links is:
```yaml
links:
- from: component_id.output_id
to: component_id.input_id
```
To achieve this change, customs serializer / deserializer and new descriptors
were implemented.
The core of the changes are in `src/model/link.rs`. The serializers simply take
a string as input and split it at the '.' character.
All the examples were updated accordingly.

Simplified links declaration in YAML 

---

zenoh-flow-examples/examples/camera-source.rs
zenoh-flow-examples/examples/counter-source.rs
zenoh-flow-examples/examples/example-buzz.rs
zenoh-flow-examples/examples/example-buzz2.rs
zenoh-flow-examples/examples/example-buzz3.rs
zenoh-flow-examples/examples/example-fizz.rs
zenoh-flow-examples/examples/face-detection.rs
zenoh-flow-examples/examples/frame-concat.rs
zenoh-flow-examples/examples/generic-sink.rs
zenoh-flow-examples/examples/manual-source.rs
zenoh-flow-examples/examples/object-detection-dnn.rs
zenoh-flow-examples/examples/random-source.rs
zenoh-flow-examples/examples/sum-and-send.rs
zenoh-flow-examples/examples/video-file-source.rs
zenoh-flow-examples/examples/video-pipeline.rs
zenoh-flow-examples/examples/video-sink.rs
zenoh-flow-examples/examples/zenoh-sink.rs
zenoh-flow/src/macros.rs
zenoh-flow/src/runtime/connectors.rs
zenoh-flow/src/runtime/message.rs
zenoh-flow/src/runtime/runner.rs
zenoh-flow/src/types.rs
zenoh-flow/tests/link.rs

To pave the way for the implementation of the deadlines the `ZFMessage`
structure needed a complete redo. This commit tries to achieve that goal.
The most noticeable changes are:
- in `types.rs` the types `*Result` were renamed to `*Output` to reflect more
their nature;
- to better separate what Zenoh Flow exposes to developers, the output of
components has been changed:
- the run function is expected to return a
`HashMap<ZFPortID, Arc<dyn DataTrait>>`,
- the output_rule function is expected to return a
`HashMap<ZFPortID, ZFComponentOutput>` where a `ZFComponentOutput` is either a
"Control Message" or some Data (i.e. a `dyn DataTrait`);
- a `ZFMessage` is either a `ZFControlMessage` or a `ZFDataMessage`.
"Intermediary" types (`ZFData`, `Message`, `ZFValue`) were removed.
All examples were …

refacto: ZFMessage complete overhaul

---

zenoh-flow-examples/examples/camera-source.rs
zenoh-flow-examples/examples/counter-source.rs
zenoh-flow-examples/examples/example-buzz.rs
zenoh-flow-examples/examples/example-fizz.rs
zenoh-flow-examples/examples/face-detection.rs
zenoh-flow-examples/examples/frame-concat.rs
zenoh-flow-examples/examples/manual-source.rs
zenoh-flow-examples/examples/object-detection-dnn.rs
zenoh-flow-examples/examples/random-source.rs
zenoh-flow-examples/examples/simple-pipeline.rs
zenoh-flow-examples/examples/sum-and-send.rs
zenoh-flow-examples/examples/video-file-source.rs
zenoh-flow-examples/examples/video-pipeline.rs
zenoh-flow-examples/examples/video-sink.rs
zenoh-flow/src/macros.rs
zenoh-flow/src/runtime/message.rs
zenoh-flow/src/traits.rs
zenoh-flow/src/types.rs

This PR contains the code that enables users to explicitly sent `raw` data as a `Vec<u8>` instead of wrapping it on some specific structure.
This is beneficial for rust->c++->rust graphs.

Add explicit support for raw data sent by the user

---

zenoh-flow/src/runtime/dataflow/instance/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
zenoh-flow/src/runtime/dataflow/instance/runners/source.rs

Refactoring of the `Runner` enum into a `trait`.
Now all the runners must implement `Runner`, this opens the possibility to dynamic loading of different runners to support different languages (e.g., Python. web-assembly).

Refactoring the Runner enum into a trait

---

cargo-zenoh-flow/src/bin/main.rs
zenoh-flow/src/model/dataflow.rs
zenoh-flow/src/model/node.rs
zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/mod.rs
zenoh-flow/src/runtime/dataflow/node.rs
zenoh-flow/src/traits.rs
zenoh-flow/src/types.rs
zenoh-flow/tests/data.rs
zenoh-flow/tests/dataflow.rs
zenoh-flow/tests/input_rule_drop.rs
zenoh-flow/tests/input_rule_keep.rs
zenoh-flow/tests/local_deadline.rs
zenoh-flow/tests/state.rs

This PR introduces the possibility to add local deadlines for the `run` method of Operator type nodes.
The deadline declaration is:
```yaml
deadline:
duration: 500
unit: ms
```
The deadline is simply _checked_ but not enforced: the `run` method of the Operator will execute until completion and, once over, we check if the time it took to execute is superior to the declared deadline.
The information is available as an `Option` in the `output_rule`:
```rust
fn output_rule(
&self,
context: &mut Context,
state: &mut State,
outputs: HashMap<PortId, Data>,
deadline_miss: Option<DeadlineMiss>,
) -> ZFResult<HashMap<PortId, NodeOutput>>;
```
This PR introduces a breaking change.

feat: local deadlines for Operator nodes

---

zenoh-flow-daemon/etc/runtime.yaml
zenoh-flow-daemon/src/daemon.rs
zenoh-flow/src/bin/runtime.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_test.rs
zenoh-flow/src/runtime/dataflow/loader.rs
zenoh-flow/src/runtime/dataflow/mod.rs
zenoh-flow/src/runtime/dataflow/node.rs
zenoh-flow/src/runtime/mod.rs
zenoh-flow/tests/dataflow.rs
zenoh-flow/tests/input_rule_drop.rs
zenoh-flow/tests/local_deadline.rs

Implementing the `Loader`, this struct comes with a configuration that allows for extensibility w.r.t. supporting different languages for the implementation of nodes of the graph.
An example configuration is:
```yaml
extentions:
- name: python
file_extension: py
source_lib: /some/path/to/target/debug/libpy_source.dylib
sink_lib:  /some/path/to/target/debug/libpy_sink.dylib
operator_lib:  /some/path/to/target/debug/libpy_op.dylib
config_lib_key: python-script
```
Which will add support for Python nodes.
The idea is that languages that require a runtime/interpreter can be supported by the means of simple wrappers and then the loader will load the wrapper and then the wrappers loads and runs the actual user code.
An example of such a pattern can be found in the [Python …

Implementing `Loader` to allow easy extensibilty with graph node implementations.

---

zenoh-flow/src/runtime/message.rs

Added `DataMessage::get_timestamp()` as it is used by C++ and Python APIs

Added DataMessage::get_timestamp()

---

zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
zenoh-flow/src/runtime/dataflow/instance/runners/source.rs
zenoh-flow/src/runtime/dataflow/loader.rs
zenoh-flow/src/runtime/dataflow/node.rs

Adding conditional compilation when dealing with dynamically loaded libraries.
In particular when the system is Unix we load the library using these flags: `libloading::os::unix::RTLD_NOW` and `libloading::os::unix::RTLD_GLOBAL`.
Because it was causing the python wrappers to not work (See https://github.com/atolab/zenoh-flow-python/issues/2) 
The solution comes from this: https://github.com/PyO3/pyo3/issues/2024

Adding flags when loading libraries on Unix, to avoid missing symbols

---

zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
zenoh-flow/src/runtime/deadline.rs

Without this fix two deadlines that end at the same Operator but that were
declared on two different inputs would trigger a deadline miss, regardless of on
which input the data was received.
For instance, if we have:
```yaml
operators:
- id: test
inputs:
- id: input-1
type: usize
- id: input-2
type: usize
deadlines:
- from:
node: past
output: out
to:
node: test
input: input-1
duration:
length: 100
unit: ms
- from:
node: past
output: out
to:
node: test
input: input-2
duration:
length: 150
unit: ms
```
Without this fix, a message that arrives on "input-1" after 200ms would have 2
deadline miss (whereas it should only have one). And a message that arrives on
"input-2" after 125ms would have 1 deadline miss (whereas it should have none).

fix: take input port id into consideration when checking E2EDeadline

---

zenoh-flow/src/model/dataflow/record.rs
zenoh-flow/src/model/dataflow/validator.rs
zenoh-flow/src/model/deadline.rs
zenoh-flow/src/model/link.rs
zenoh-flow/src/model/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/sink_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/source_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/mod.rs
zenoh-flow/src/runtime/deadline.rs
zenoh-flow/tests/dataflow.rs
zenoh-flow/tests/e2e_deadline.rs
zenoh-flow/tests/input_rule_drop.rs
zenoh-flow/tests/local_deadline.rs

This modification is in preparation for the implementation of Loops. Indeed, for
a Loop, the "from" (resp. "to") corresponds to an Input (resp. Output).
Renaming both aims at removing this ambiguity.

refacto: rename `{From|To}Descriptor` to `{Output|Input}Descriptor`

---

zenoh-flow/src/runtime/dataflow/loader.rs

In this PR we changed the flags used when loading nodes. 
Now the flags are:
- `RTLD_NOW` so all symbols are loaded when loading the `*.so`. 
- `RTLD_LOCAL` so all symbols stay local, therefore if multiple libraries have the same symbols they do not clash.
But this means that language wrappers may need to load the language runtime explicitly (look at [Python Wrappers](https://github.com/atolab/zenoh-flow-python/tree/exp/libloading)) 
--- 
:warning: Please before merging test that the `runtime` is able to load `rust`, `C++`, and `Python` nodes.

Updating libloading flags, to prevent C++ nodes to hang

---

zenoh-flow-ctl/src/main.rs
zenoh-flow-daemon/src/daemon.rs
zenoh-flow/src/runtime/dataflow/instance/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
zenoh-flow/src/runtime/dataflow/instance/runners/source.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_test.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/sink_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/source_e2e_deadline_tests.rs
zenoh-flow/src/runtime/mod.rs
zenoh-flow/src/types.rs

This PR contains the code with the initial implementation of logging and replay.
- Sources can be **recorded** 
- Data coming from sources is serialized and sent to zenoh in order to be stored in some time-series storages
- Markers are sent when starting and stopping the logging
- Users can read the recording directly from zenoh using the key expression provided when recording.
- Sources can be **replayed** 
- Data will come from zenoh and the replay will happen in order and with the same pace of the recording.
In order for the logging/replay to work a zenoh storage in InfluxDB needs to be present, and example configuration of zenoh with a storage is provided below
```json
{
"listeners": ["tcp/127.0.0.1:7887"],
"link_state":true,
"plugins_search_dirs":["/usr/lib/"],
"plugins":{ …
```

Initial implementation of record and replay

---

zenoh-flow-daemon/Cargo.toml
zenoh-flow-daemon/resources/rpm/template.hbs
zenoh-flow/resources/debian/zenoh-flow
zenoh-flow/resources/rpm/zenoh-flow
zenoh-flow/resources/rpm/zenoh-flow.spec

This PR implements #73, providing meta-package definitions, for both Debian files and rpm files.
It also updates the dependencies for zenoh-flow-daemon.

Meta packages from RPM and deb

---

cargo-zenoh-flow/src/bin/main.rs
zenoh-flow-ctl/src/main.rs
zenoh-flow/src/error.rs
zenoh-flow/src/lib.rs
zenoh-flow/src/model/dataflow/descriptor.rs
zenoh-flow/src/model/dataflow/record.rs
zenoh-flow/src/model/dataflow/validator.rs
zenoh-flow/src/model/loops.rs
zenoh-flow/src/model/mod.rs
zenoh-flow/src/model/node.rs
zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/source.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_test.rs
zenoh-flow/src/runtime/dataflow/mod.rs
zenoh-flow/src/runtime/dataflow/node.rs
zenoh-flow/src/runtime/loops.rs
zenoh-flow/src/runtime/message.rs
zenoh-flow/src/runtime/mod.rs
zenoh-flow/src/runtime/token.rs
zenoh-flow/src/traits.rs
zenoh-flow/src/types.rs
zenoh-flow/tests/dataflow.rs
zenoh-flow/tests/e2e_deadline.rs
zenoh-flow/tests/input_rule_drop.rs
zenoh-flow/tests/local_deadline.rs
zenoh-flow/tests/loop.rs
zenoh-flow/tests/validator.rs

A Loop is written as following:
```yaml
loops:
- ingress: A
egress: B
feedback_port: feedback
port_type: int
is_infinite: false
```
The `ingress` is the starting point of a Loop. The `egress` is where it can
end. Each time a message goes through a Loop, Zenoh Flow either:
- attaches a new `LoopContext` to it,
- updates the already attached `LoopContext`.
For a given message, the `LoopContext` provides:
- the timestamp at which it entered the Loop,
- the timestamp at which the current iteration started,
- the duration of the last iteration,
- the iteration count (if the Loop was declared as finite).
A Loop between Operators can only exist if the following constraints are respected:
- the Ingress (starting point of the Loop) has a single output,
- the Egress (ending point) has a single …

feat: add Loop support

---

cargo-zenoh-flow/Cargo.toml
zenoh-flow-ctl/Cargo.toml
zenoh-flow-daemon/Cargo.toml
zenoh-flow-derive/Cargo.toml
zenoh-flow/Cargo.toml
zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs

This PR fixes #81.
Now `NodeRunner::run_stopplable` is async, it uses async closures, and `NodeRunner::start` uses `task::spawn` instead of `task::spawn_blocking`.

Removing task::spawn_blocking and task::block_on, using async closures, fixes #81

---

cargo-zenoh-flow/Cargo.toml
cargo-zenoh-flow/src/bin/main.rs
zenoh-flow-ctl/Cargo.toml
zenoh-flow-ctl/src/main.rs
zenoh-flow-daemon/Cargo.toml
zenoh-flow-daemon/src/main.rs
zenoh-flow/Cargo.toml
zenoh-flow/src/error.rs

This PR replaces all the usage of `structopt` with `clap`.
`structopt` is now deprecated: https://docs.rs/structopt/latest/structopt/#maintenance

Using clap instead of structopt

---

zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
zenoh-flow/src/runtime/dataflow/instance/runners/source.rs

This PR solves a concurrency issue that may cause starvation of the stop task for a `Runner`.
Adding an explicit `yield` in the `run` function allows to give back the control to the scheduler and if other tasks are ready to run them, thus avoiding starvation.
If no other tasks are ready the task is run immediately.

Explict yield in runners to avoid starvation of the stop task.

---

zenoh-flow/src/model/dataflow/descriptor.rs
zenoh-flow/src/runtime/dataflow/loader.rs

With this commit, when a library is not found, the incriminated path is shown.

fix: show path of file not found when loading fails

---

zenoh-flow-daemon/src/daemon.rs
zenoh-flow/src/runtime/dataflow/instance/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
zenoh-flow/src/runtime/resources.rs

This PR fixes an issue with the `DataflowInstance` not exposing any function to call the `finalize` function for any nodes of the graph.
Now the `DataflowInstance` expose the `clean_node` function that calls the `finalize` function for a given node.
The `zenoh-flow-daemon` calls this function when cleaning an instance.

Fixing finalize function not being called when cleaning a data flow intance

---

.github/workflows/ci.yml
README.md
cargo-zenoh-flow/Cargo.toml
cargo-zenoh-flow/src/bin/main.rs
cargo-zenoh-flow/src/error.rs
cargo-zenoh-flow/src/templates.rs
cargo-zenoh-flow/src/utils.rs

This PR extends `cargo zenoh-flow`, providing the possibility to generate boilerplates for **Python** and **C++** Zenoh Flow nodes.
This addresses #112 #111

cargo zenoh-flow to provide boilerplates for Python and C++ nodes

---

zenoh-flow/src/runtime/resources.rs

This fixes an issue in the `get_runtime_info_by_name` function that instead of returning the correct `RuntimeInfo` returns the first one found in Zenoh

Fixing get_runtime_info_by_name function

---

zenoh-flow/src/model/dataflow/descriptor.rs
zenoh-flow/src/model/dataflow/flag.rs
zenoh-flow/src/model/dataflow/mod.rs
zenoh-flow/src/model/dataflow/record.rs
zenoh-flow/src/model/dataflow/validator.rs
zenoh-flow/tests/validator.rs

A flag allows user to specify which part of a data flow to activate or
deactivate by declaring a set of nodes.
Nodes that are not present under any flag are activated.
The validity of toggled flags is checked, raising an error if need be. For flags
that are not toggled, only a warning is emitted.

feat: optionally toggle parts of a data flow using flags

---

.gitignore
zfctl/Cargo.toml
zfctl/src/main.rs

Rust does not expand the `~` correctly. This commit leverages the `dirs` crate
to get it --- as recommended by the official documentation:
https://doc.rust-lang.org/std/env/fn.home_dir.html
(the dependencies in Cargo.toml were also sorted alphabetically)

fix: get $HOME dir through crate `dirs`

---

.github/workflows/ci.yml

Today's CI pipeline used in PRs takes way too much time as it builds for a total of 16(!!!) platforms.
So this PR simplifies it to run only on `ubuntu-latest` and `macos-latest` as the other platforms can be covered by a nightly CI (that can also build and make available the artifacts).

Simplify CI pipeline for PRs.

---

zenoh-flow-daemon/src/runtime.rs
zenoh-flow-daemon/src/worker.rs
zenoh-flow/src/zfresult.rs

Before:
```
[2023-02-15T08:55:05Z ERROR zenoh_flow_daemon::worker] [Worker: 0] Got error when running Job: d4b2f452-bb3b-4cfc-8384-2d516dbe9142 - ZenohError
```
After:
```
[2023-02-15T08:55:05Z ERROR zenoh_flow_daemon::worker] [Worker: 0] Got error when running Job: d4b2f452-bb3b-4cfc-8384-2d516dbe9142 - ZenohError None at zenoh-flow/src/zfresult.rs:279. Description: Some("IOError Some(No such file or directory (os error 2): /home/ato/Workspace/zenoh-flow-examples/montblanc/target/release/libhebron.so) at zenoh-flow/src/utils.rs:58. Description: Some(\"No such file or directory (os error 2): /home/ato/Workspace/zenoh-flow-examples/montblanc/target/release/libhebron.so\")")
```

Fix Logging errors

---

zenoh-flow-daemon/src/daemon.rs
zenoh-flow-daemon/tests/configuration.rs
zenoh-flow/Cargo.toml
zenoh-flow/src/lib.rs
zenoh-flow/src/model/descriptor/link.rs
zenoh-flow/src/model/record/connector.rs
zenoh-flow/src/model/record/dataflow.rs
zenoh-flow/src/model/record/link.rs
zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
zenoh-flow/src/runtime/dataflow/instance/mod.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/runtime/dataflow/mod.rs
zenoh-flow/src/runtime/mod.rs
zenoh-flow/src/types/context.rs
zenoh-flow/src/types/message.rs
zenoh-flow/src/utils.rs
zenoh-flow/tests/dataflow.rs

Currently, Zenoh-Flow connectors and built-in Zenoh Sinks do not use the Shared Memory transport of zenoh. 
Using it means exposing some configuration to users, as the Shared Memory has to be allocated and there is no one-size-fits-them-all that we can automatically use when allocating it.
To this extent, the proposal for connectors (the internal components automatically do the zenoh connection when things are on different runtimes) and one for the built-in sink.
The connectors are the components that take care of sending user-plane data between two nodes, of the same flow, running on two different runtimes. Connectors are generated automatically by Zenoh Flow when instantiating the graph.
When using shared memory this connector, the one on sending side, must allocate a shared memory area …

Using Zenoh's Shared Memory Buffer

---

zenoh-flow-daemon/etc/runtime.yaml
zenoh-flow-daemon/src/daemon.rs
zenoh-flow-plugin/etc/zenoh-zf-plugin.json
zenoh-flow/src/lib.rs
zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/runtime/mod.rs
zenoh-flow/src/types/context.rs
zenoh-flow/tests/dataflow.rs

Adding a new configuration parameter to enable/disable the automatic Shared Memory transport over Zenoh.
Shared Memory can cause `SIGBUS` errors on docker containers, therefore it is disabled by default.
Configuration file look like this:
```yaml
---
pid_file : /var/zenoh-flow/runtime.pid
path : /etc/zenoh-flow
extensions: /etc/zenoh-flow/extensions.d
zenoh_config: /etc/zenoh-flow/zenoh-daemon.json
worker_pool_size: 4
use_shm: false #change to true to enable, WARNING in docker this can cause BUS Errors!!!
```

Possibility to enable/disable automatic shared memory transport over Zenoh

---

zenoh-flow-daemon/Cargo.toml
zenoh-flow/Cargo.toml
zfctl/Cargo.toml

zenoh-rpc was requiring the version "=1.0.23" of the `quote` crate which, somehow, forced Cargo to:
- bump `pest_meta` to the version "2.6.0",
- bump `pest_generator` to the version "2.5.6".
Unfortunately these crates are incompatible, eventually preventing us from building Zenoh-Flow.

deps: bump version of zrpc to 0.6.1-alpha.1

---

zenoh-flow/src/io/output.rs
zenoh-flow/src/io/tests/input-tests.rs
zenoh-flow/src/io/tests/output-tests.rs
zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/traits.rs
zenoh-flow/src/types/message.rs
zenoh-flow/tests/dataflow.rs

These commits try to minimize the number of allocations performed when
serializing data. For this end, the connector and built-in Source now create
internal `Vec<u8>` buffers that are reused whenever a message is serialized.
This change should hopefully (slightly) improve performance.

feat: reuse buffer when serializing

---

Cargo.lock
Cargo.toml
cargo-zenoh-flow/Cargo.toml
cargo-zenoh-flow/src/utils.rs
zenoh-flow-daemon/Cargo.toml
zenoh-flow-derive/Cargo.toml
zenoh-flow-plugin/Cargo.toml
zenoh-flow/Cargo.toml
zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
zenoh-flow/src/runtime/resources.rs
zfctl/Cargo.toml

The updates that induced changes were:
- (Zenoh-Flow) flume 0.10 -> 0.11: as we were explicitly defining the Subscriber (in particular the `Receiver<Sample>`), the version of flume we were using was tied to Zenoh's. By using Zenoh's `FlumeSubscriber`, we can update the version of flume independently of Zenoh.
- (cargo-zenoh-flow) toml 0.5 -> 0.7: parsing must be done via a String rather than via slice.

chores: update dependencies to latest versions

---

zenoh-flow-commons/src/lib.rs
zenoh-flow-commons/src/vars.rs
zfctl/src/instance_command.rs
zfctl/src/main.rs

This will allow reusing this logic in all Zenoh-Flow executable.

refacto(commons): move `parse_vars` function in `commons` crate

---

Cargo.lock

The `tracing` and `tracing-subscriber` dependencies were, somehow, forgotten.

fix(deps): Cargo.lock dependencies for standalone runtime

---

zenoh-flow-descriptors/Cargo.toml
zenoh-flow-descriptors/src/flattened/tests.rs
zenoh-flow-descriptors/src/io.rs
zenoh-flow-records/Cargo.toml
zenoh-flow-records/src/dataflow.rs
zenoh-flow-records/src/tests.rs

The current implementation is not as optimised as it deserves to be. In short, if the shared memory is enabled, then every time Zenoh-Flow will send data through Zenoh (be it between runtimes on the same host or on different hosts) it will first attempt to send it through shared memory.
As it is now, sending data through shared memory requires a copy as the data does not reside inside a shared memory buffer (it must be copied from the programs memory to the shared memory).
In cases where there is actually a shared memory buffer, this could still lead to better performance. However, as the current design enables it *everywhere*, if there is no shared memory then the data is copied twice: (i) from the programs memory to the shared memory and (ii) from the shared memory to a Zenoh buffer to …

refacto: disable shared-memory feature by default

---

zenoh-flow-commons/src/lib.rs
zenoh-flow-commons/src/utils.rs
zenoh-flow-daemon/src/lib.rs
zenoh-flow-descriptors/src/uri.rs
zenoh-flow-runtime/src/loader/mod.rs
zenoh-flow-standalone-runtime/src/main.rs
zfctl/src/instance_command.rs

It's a bit of a nitpick but we're attempting to parse a descriptor (in our case) from the file rather than trying to load anything.

rename(commons): `try_load_from_file` to `try_parse_from_file`

---

zenoh-flow-descriptors/src/flattened/nodes/operator.rs
zenoh-flow-descriptors/src/flattened/tests.rs
zenoh-flow-descriptors/src/nodes/mod.rs
zenoh-flow-descriptors/src/uri.rs
zenoh-flow-descriptors/tests/descriptors/data-flow-recursion.yml

The `descriptor` field of a Node is, in fact, a Url. This commit makes that change which allows us to remove one error scenario from our code base.

refacto(descriptors): use `Url` instead of `Arc<str>`

---

zenoh-flow-commons/src/configuration.rs
zenoh-flow-commons/src/vars.rs

This commit tries to explain how these structures are leveraged by Zenoh-Flow and focuses in particular and how they are merged.
Users can declare a `Configuration` and `Vars` at several locations when describing their application. When this happens Zenoh-Flow merges these declaration in a specific way. This commit tries to clarify the "merge-strategy" employed.

doc(commons): improve documentation of Configuration and Vars

---

zenoh-flow-descriptors/src/nodes/mod.rs
zenoh-flow-descriptors/src/nodes/operator/mod.rs

These fields were wrongfully forgotten during the major refactoring.

refacto(descriptors): only specify runtime in `mapping` section

---

zenoh-flow-descriptors/src/dataflow.rs
zenoh-flow-descriptors/src/flattened/nodes/operator.rs
zenoh-flow-descriptors/src/flattened/nodes/sink.rs
zenoh-flow-descriptors/src/flattened/nodes/source.rs
zenoh-flow-descriptors/src/lib.rs
zenoh-flow-descriptors/src/nodes/builtin/zenoh.rs
zenoh-flow-descriptors/src/nodes/mod.rs
zenoh-flow-descriptors/src/nodes/operator/composite.rs
zenoh-flow-descriptors/src/nodes/operator/mod.rs
zenoh-flow-descriptors/src/nodes/sink.rs
zenoh-flow-descriptors/src/nodes/source.rs

The different "base" node descriptors (i.e. not flattened) were not designed to be exposed in the public API.
This commit changes the visibility of these structures to `pub(crate)`.

refacto(descriptors): change visibility of base descriptors

---

zenoh-flow-descriptors/src/flattened/nodes/operator.rs
zenoh-flow-descriptors/src/flattened/nodes/sink.rs
zenoh-flow-descriptors/src/flattened/nodes/source.rs
zenoh-flow-descriptors/src/flattened/tests.rs
zenoh-flow-descriptors/src/nodes/builtin/zenoh.rs
zenoh-flow-descriptors/src/nodes/mod.rs
zenoh-flow-descriptors/src/nodes/operator/mod.rs
zenoh-flow-descriptors/src/nodes/sink.rs
zenoh-flow-descriptors/src/nodes/source.rs
zenoh-flow-descriptors/tests/descriptors/data-flow.yml

Before this commit, the `description` field for each node was mandatory. It is now optional for all.
Additionally, when two descriptions are provided (e.g. inside the descriptor file of a node + when it is included in the data flow descriptor), the "outer" description will overwrite the "inner" one. See the modifications made in the flattened tests.

refacto(descriptors): make description section optional

---

zenoh-flow-descriptors/src/flattened/validator/mod.rs
zenoh-flow-descriptors/src/flattened/validator/tests.rs

Conceptually speaking, a data flow that has no Source will never perform any transformation on any data as it will never receive any.
Similarly, a data flow that has no Sink will never output anything, making it a close loop.
This commit ensures that a valid (flattened) data flow has at least one Source and one Sink.

fix(descriptors): a valid flow must have a Source and a Sink

---

zenoh-flow-descriptors/src/dataflow.rs
zenoh-flow-descriptors/src/flattened/dataflow.rs
zenoh-flow-descriptors/src/flattened/tests.rs

Conceptually, a data flow does not need an Operator to be valid.
This commit allows omitting the `operators` section.

fix(descriptors): make operators section optional

---

zenoh-flow-descriptors/Cargo.toml
zenoh-flow-descriptors/src/dataflow.rs
zenoh-flow-descriptors/src/flattened/dataflow.rs
zenoh-flow-descriptors/src/flattened/tests.rs
zenoh-flow-records/src/dataflow.rs
zenoh-flow-records/src/tests.rs

Even though internally an `InstanceId` is a wrapper around a `Uuid`, by using the former everywhere we provide a more consistent API.

refacto: use `InstanceId` instead of `Uuid` for consistency

---

zenoh-flow-nodes/src/messages.rs

- `RecordingMetadata`
- `ControlMessage`

clean(nodes): remove unused recording structures

---

zenoh-flow-nodes/src/traits.rs
zenoh-flow-runtime/src/instance.rs
zenoh-flow-runtime/src/runners/builtin/zenoh/source.rs
zenoh-flow-runtime/src/runners/mod.rs
zenoh-flow-runtime/src/runtime/mod.rs

The purpose of the `abort` method is to forcefully abort the execution of a node. We cannot recover from an error, hence there is no use in allowing returning one.

refactor: `on_abort` hook returns no error

---

zenoh-flow-descriptors/src/flattened/validator/mod.rs
zenoh-flow-descriptors/src/flattened/validator/tests.rs
zenoh-flow-nodes/src/io/inputs.rs
zenoh-flow-nodes/src/io/tests/input-tests.rs

Handling multiple incoming links to the same Input introduced unnecessary complexity on multiple fronts: internally, to manage the errors and at the API level, on how to expose that some links failed yet a result is still produced (a form of "partial error").
By ensuring that an Input only accepts a single Output we simplify our API.

refactor: an Input only accepts a single Output

---

Cargo.lock
zenoh-flow-daemon/Cargo.toml
zenoh-flow-daemon/src/configuration.rs
zenoh-flow-runtime/Cargo.toml
zenoh-flow-runtime/src/loader/extensions.rs
zenoh-flow-runtime/src/loader/mod.rs

This commit ensures that the libraries that are used to support additional programming languages (i.e. "extensions") expose the correct symbols.
Hence, if a library is not suitable (wrong path, wrong symbol) the Zenoh-Flow runtime will raise an error while parsing its configuration, not when trying to load a data flow.
To keep the actual tests from consistently failing, the feature "test-utils" was introduced in the `zenoh-flow-runtime` crate which is enabled by the `zenoh-flow-daemon` crate only as a dev-dependency.

feat(runtime): check extensions libraries before loading

---

zenoh-flow-daemon/src/lib.rs
zenoh-flow-runtime/src/lib.rs
zenoh-flow-runtime/src/loader/extensions.rs
zenoh-flow-runtime/src/loader/mod.rs
zenoh-flow-standalone-runtime/src/main.rs

Users manually creating a Zenoh-Flow runtime or daemon could need to add extensions. This commit makes it easier to add extensions by exposing the function `try_add_extension` both at the Loader and Daemon levels.
The `Extension` structure was also made public with methods to access the values of the different fields composing it.

refactor: expose `try_add_extension` at Loader and Daemon

---

Cargo.lock
zenoh-flow-daemon/src/instances/abort.rs
zenoh-flow-daemon/src/instances/delete.rs
zenoh-flow-daemon/src/instances/start.rs
zenoh-flow-runtime/Cargo.toml
zenoh-flow-runtime/src/instance.rs
zenoh-flow-runtime/src/lib.rs
zenoh-flow-runtime/src/runtime/load.rs
zenoh-flow-runtime/src/runtime/mod.rs
zfctl/Cargo.toml
zfctl/src/instance_command.rs

The main changes introduced by this commit pertain to the `InstanceState` structure.
Two variants were added:
- Creating
- Failed
For each variant a timestamp was added, e.g. `Creating(Timestamp)`, such that users can track when modifications were performed on their data flow.
The `Failed` state had additional consequences, on the runtime, daemon and zfctl.
The purpose of introducing this state is to allow users to keep track of what went wrong when trying to create their data flow. In order to do so, we need to keep the failed instance within the runtime --- we cannot immediately drop it as was done before.
If we keep the failed instance, we suddenly "allow" start / abort requests on it. Which should not be done. The changes on the runtime, daemon and zfctl address this problem.

refactor: improve data flow state management

---

zenoh-flow-runtime/src/loader/extensions.rs

- added the `repr(transparent)` as it is just a newtype
- implemented `From<Extension>` for the HashMap to facilitate converting it into a… HashMap (useful to then merge two Extensions),
- changed the signature of the `try_add_extension` method to accept `impl Into<PathBuf>` (making it possible to pass str)

refactor(runtime): small improvements over Extensions struct

---

zenoh-flow-runtime/src/lib.rs
zenoh-flow-runtime/src/loader/mod.rs

The Loader is part of the internals of Zenoh-Flow, there is no need to expose it.
Note that this change was made possible thanks to the introduction of the RuntimeBuilder (and the main motivation behind it).

refactor(runtime): make Loader structure private

---

justfile
zenoh-flow-daemon/src/daemon/mod.rs

* justfile: added two separate actions to build the crate with and without the feature "plugin".
* daemon/mod.rs: used the fully qualified path when using the `anyhow!` macro.

fix(daemon): missing `anyhow` import without "plugin" feature

---

zenoh-flow-daemon/src/daemon/mod.rs
zenoh-flow-daemon/src/queries/instances/delete.rs
zenoh-flow-daemon/src/queries/instances/mod.rs

This commit makes the Daemon delete the instances it manages before stopping. In particular, for all the data flow instances that are spanning on multiple Daemons, it will ask the involved Daemons to also delete them.
* queries/instances/delete.rs: make the function `delete_instance` return a `JoinHandle` so I can await it. This is needed when stopping the Daemon as, if these are not awaited, the Daemon will stop before the requests to delete have been sent out.
* queries/instances/mod.rs:
- make all submodules `pub(crate)` such that they can be called from other submodules in the zenoh_flow_daemon crate. I was interested more specifically in the delete crate as I needed to access the `delete_instance` function.
- as `delete_instance` now returns a `JoinHandle`, the match case had to be …

feat(daemon): delete all instances before stopping the Daemon

---

justfile
zenoh-flow-runtime/src/runtime/builder.rs
zenoh-flow-runtime/src/runtime/load.rs

The crate `zenoh_flow_runtime` was not compiled, in our tests, with the different flags turned on / off, which led to few imports that were not guarded.
This commit fixes these errors and adds the necessary tests in the `justfile`.
* justfile: add two compilation checks.
* runtime/builder.rs:
- guard the zenoh import below a `cfg(feature)` directive,
- removed the `anyhow` import and instead fully qualify their usage.
* runtime/load.rs: guard the imports of the builtin Zenoh source / sink with a `cfg(feature)` directive.

fix(runtime): add missing `cfg(feature)`

---

zfctl/src/main.rs
zfctl/src/runtime_command.rs
zfctl/src/utils.rs

This commit allows specifying the name of a Runtime in order to force `zfctl` to interact with it.
If several Runtimes share the same name, `zfctl` will abort its execution asking users to specify their unique identifier.
* zfctl/src/main.rs:
- add the mutually exclusive options `-i` (`--id`) and `-n` (`--name`) to select a Runtime when issuing an instance command,
- refactored the way the `orchestrator_id` is obtained, taking into account the possibly provided name or id,
- renamed the inner variable `r` to `command` for consistency.
* zfctl/src/runtime_command.rs:
- moved the `get_all_runtimes` function the `utils` module,
- modified the `Status` command to allow providing a name or an id.
* zfctl/src/utils.rs: a file that regroups the different ways of obtaining a Runtime identifier:
- …

feat(zfctl): allow selecting a Runtime via its `name`

---

zfctl/src/instance_command.rs

The rust doc was wrongly picking them as code.
* zfctl/src/instance_command.rs: remove backtick.

docs(zfctl): remove backtick quotes

---

zenoh-flow-commons/src/configuration.rs
zenoh-flow-commons/src/deserialize.rs
zenoh-flow-commons/src/utils.rs
zenoh-flow-commons/src/vars.rs

* zenoh-flow-commons/src/configuration.rs: improve documentation of `Configuration` structure.
* zenoh-flow-commons/src/deserialize.rs: rephrased errors to use affirmative "tense".
* zenoh-flow-commons/src/utils.rs:
- internal documentation of `deserializer` function (to obtain the function that would deserialise a structure based on the Path of the file),
- internal documentation of error cases when attempting to parse a structure from a file.
* zenoh-flow-commons/src/vars.rs: improve documentation and explain error case when parsing `vars` from a String.

docs(commons): improve / rephrase documentation

---

zfctl/src/main.rs

Providing a Zenoh configuration allows, among other advantages, connecting to remote Zenoh networks.
* zfctl/src/main.rs: add the '-z' option to provide the path to a Zenoh configuration.

feat(zfctl): allow providing an optional Zenoh configuration

---

justfile
zenoh-flow-daemon/src/daemon/configuration.rs
zenoh-flow-daemon/src/daemon/mod.rs
zenoh-flow-daemon/src/lib.rs
zenoh-plugin-zenoh-flow/Cargo.toml

Because of the way features work in Rust, in particular the fact that they are additive, it is impossible to have mutually exclusive features.
In the case of the `zenoh-flow-daemon` crate, we wanted to have the feature "plugin" enabled for the `zenoh-plugin-zenoh-flow` crate and not for the `zenoh-flow-standalone-daemon`. Having that feature enabled for one, enabled it for all crates --- which was not the desired behaviour.
To achieve the desired behaviour we should: (i) remove the feature and (ii) separate the Zenoh configuration from the Zenoh-Flow configuration.
This commit addresses (i).
* justfile: removed the build test with `--features plugin` as this feature no longer exists.
* zenoh-flow-daemon/src/daemon/configuration.rs: removed the embedded `ZenohConfiguration` structure from …

refactor(daemon): removed feature "plugin"

---

Cargo.lock
Cargo.toml
zenoh-flow-daemon/Cargo.toml

This is the reason why the release of version `0.6.0-alpha` failed
starting at the `zenoh-flow-daemon` crate: the constraint was not strict
enough, it authorised pulling the version 4.5.x which require a MRSV of
1.74.
* Cargo.toml: force clap to be at 4.4.x (which requires a MRSV of 1.70)
--------
This is, unfortunately, a historical artefact: before the major
crate-split the crate `zenoh-flow-daemon` was containing the executable
and thus needed to provide a CLI (leveraging `clap`).
This dependency should have been removed.
* Cargo.lock: removed clap from the dependencies of zenoh-flow-daemon
* zenoh-flow-daemon/Cargo.toml: removed clap from the dependencies

fix: clap dependency

---

zenoh-flow-daemon/src/daemon/configuration.rs
zenoh-flow-daemon/src/daemon/mod.rs

`serde_yaml` consistently failed to deserialise the configuration of Zenoh-Flow when the extensions were declared in another file.
This commit removes the possibility of declaring the extensions in another file.
* zenoh-flow-daemon/src/daemon/configuration.rs:
- removed the `ExtensionsConfiguration` enum,
- removed the associated tests,
* zenoh-flow-daemon/src/daemon/mod.rs:
- updated the code due to the removal of the `ExtensionsConfiguration` enum.

refactor(daemon): configuration of extensions must be inline

---

zenoh-flow-nodes/src/context.rs
zenoh-flow-runtime/src/loader/mod.rs
zenoh-flow-runtime/src/runtime/load.rs

Fixes #246.
As explained in #246, providing the path of the library that Zenoh-Flow loads is a requirement for developing extensions. For instance, in Python, the `pyo3` library needs to load the script.
This change adds the accessor method `library_path` to the `Context` structure, that returns a reference to the full path of the library being loaded.
* zenoh-flow-nodes/src/context.rs:
- add the library_path field to the Context structure,
- update the constructor accordingly,
- add the accessor method `library_path()`.
* zenoh-flow-runtime/src/loader/mod.rs:
- update the Loader structure to also store the path of the library that is being loaded,
- update the code to account for the path of the library being also stored.
* zenoh-flow-runtime/src/runtime/load.rs:
- remove the `Context` …

feat(nodes): pass the library path in the context

---

Cargo.lock
Cargo.toml
tests/zenoh-plugin-zenoh-flow.json
zenoh-plugin-zenoh-flow/Cargo.toml
zenoh-plugin-zenoh-flow/src/lib.rs

The main motivation to make that change is the ability to keep the Rust version to 1.72.
Indeed, in this version of Zenoh there is no longer an unused dependency on `Clap` of `zenoh-utils` which — because Clap does not respect SemVer — forced several crates to be released with Rust 1.74.
* Cargo.lock: update dependencies.
* Cargo.toml:
- changed the version of the Zenoh crate to 0.11.0-rc.3,
- `zenoh-plugin-trait` crate: removed the `default-features = false` as it no longer applies,
- `zenoh` crate:
- removed the `shared-memory` feature,
- added the `unstable` and `plugins` features.
* tests/zenoh-plugin-zenoh-flow.json: a Zenoh configuration that attempts to load Zenoh-Flow as a plugin.
* zenoh-plugin-zenoh-flow/Cargo.toml: removed the `no_mangle` feature as it is no longer needed.
* …

deps: upgrade Zenoh to 0.11.0-rc.3

---

zenoh-flow-runtime/src/runtime/load.rs

* zenoh-flow-runtime/src/runtime/load.rs: add logging information when loading a source, operator, sink.

feat: add logging when loading nodes

---

zenoh-plugin-zenoh-flow/Cargo.toml
zenoh-plugin-zenoh-flow/src/lib.rs

Having this feature and, in particular, the ability to disable it, allows statically linking the Zenoh-Flow plugin to Zenoh.
This feature is enabled by default.
* zenoh-plugin-zenoh-flow/Cargo.toml: added the `dynamic_plugin` feature.
* zenoh-plugin-zenoh-flow/src/lib.rs: only call the macro `declare_plugin!` if the feature `dynamic_plugin` is enabled.

feat(zenoh-plugin-zenoh-flow): provide "dynamic_plugin" feature

---

zenoh-flow-nodes/src/lib.rs

To create the Python bindings and re-expose these types in Python, accessing them was required.
By exposing them in the `prelude` of the `zenoh-flow-nodes` crate, users are not required to add a dependency on `zenoh-flow-commons` or `uhlc`.
* zenoh-flow-nodes/src/lib.rs: expose in the prelude:
- InstanceId,
- NodeId,
- RuntimeId,
- uhlc::Timestamp.

fix(zenoh-flow-nodes): expose common types in prelude

---

zenoh-flow-runtime/src/loader/mod.rs

When the loading of a wrapper shared library failed, the path of the library to wrap was displayed instead of that of the wrapper.
This commit fixes this error and adds debug information when a wrapper shared library is about to be loaded.
* zenoh-flow-runtime/src/loader/mod.rs:
- add debug logging information,
- show wrapper path in error when loading it failed.

fix(zenoh-flow-runtime): log wrapper path when failing to load it

---

zenoh-flow-nodes/src/messages.rs
zenoh-flow-runtime/src/runners/builtin/zenoh/sink.rs

Writing the Python bindings highlighted a tiny nuisance of the `Deref` trait: in order to access a Payload, an explicit turbofished call to Deref was required, which was not particularly ergonomic.
This commit introduces accessors for both the `payload` and `timestamp` fields of a `LinkMessage`.
The method `get_timestamp` was deprecated in favour of `timestamp`. This change is purely aesthetic and for coherence purposes.
* zenoh-flow-nodes/src/messages.rs:
- removed the implementation of the Deref trait,
- added an accessor `payload()`,
- added an accessor `timestamp()`,
- deprecated the accessor `get_timestamp()` in favour of `timestamp()`.
* zenoh-flow-runtime/src/runners/builtin/zenoh/sink.rs: as the Deref trait is no longer implemented on `LinkMessage`, a call to `payload()` is …

fix(zenoh-flow-nodes): provide accessors on `LinkMessage`

---

Cargo.lock
zenoh-flow-commons/Cargo.toml
zenoh-flow-commons/src/utils.rs

If the `Vars` section was not present in a file that is parsed by the function `try_parse_from_file` then an error would be thrown.
This commit changes the behaviour of the function such that if it is missing, no error is returned and instead a log message is recorded.
* Cargo.lock: added dependency `tracing`.
* zenoh-flow-commons/Cargo.toml: added dependency `tracing`.
* zenoh-flow-commons/src/utils.rs: instead of throwing an error if the `Vars` section is missing, log a debug message and continue the normal execution.

fix(commons): do not fail without `Vars` section

---

zfctl/src/instance_command.rs

As mentioned in a previous discussion, the `zfctl instance list` command did not output anything to the terminal.  
This PR adds the following table output:
```
+---------------+-------------+----------------+
| Instance Name | Instance ID | Instance State |
+===============+=============+================+
|               |             |                |
+---------------+-------------+----------------+
```

Add `InstanceQuery::List` reply

---

zfctl/src/daemon_command.rs
zfctl/src/instance_command.rs
zfctl/src/main.rs
zfctl/src/run_local_command.rs
zfctl/src/utils.rs

This commit brings some improvements to the outputted logs when launching `zfctl` and the `zfctl daemon` command.
The most notable additions are:
- when starting a Zenoh-Flow Daemon, its name and Zenoh ID will be logged,
- the `RUST_LOG` environment variable will be used if specified,
- the default logging level was set to `zfctl=info,zenoh_flow=info`.
* zfctl/src/daemon_command.rs:
- Added a `span` at the top of the `run` method to be used within the `async` block.
- Reworked the code to not `panic!` when an error occurred but instead return it and/or add logs.
* zfctl/src/instance_command.rs:
- Properly display the id of the newly created instance.
- Display a command to check for the status of a newly created instance.
* zfctl/src/main.rs:
- Read the environment variable RUST_LOG to …

refactor(zfctl): improve logs
