- README.md
Minor change in the readme as it wasn't mentioned earlier (it seems)
> update readme run examples on unix

- zenoh-flow-ctl/src/main.rs
- zenoh-flow-daemon/src/runtime.rs
- zenoh-flow-examples/examples/simple-pipeline.rs
- zenoh-flow-examples/examples/video-pipeline.rs
- zenoh-flow-examples/graphs/car-pipeline-multi-runtime.yaml
- zenoh-flow-examples/graphs/dnn-object-detection-multi-runtime.yaml
- zenoh-flow-examples/graphs/dnn-object-detection.yaml
- zenoh-flow-examples/graphs/face-detection-multi-runtime.yaml
- zenoh-flow-examples/graphs/face_detection.yaml
- zenoh-flow-examples/graphs/fizz-buzz-multiple-runtimes.yaml
- zenoh-flow-examples/graphs/random_source.yaml
- zenoh-flow-examples/graphs/simple_pipeline.yaml
- zenoh-flow-examples/graphs/stereo-car-camera-pipeline.yaml
- zenoh-flow-examples/graphs/video_pipeline.yaml
- zenoh-flow-examples/graphs/zface_detection.yaml
- zenoh-flow-examples/graphs/zvideo_pipeline.yaml
- zenoh-flow/src/bin/runtime.rs
- zenoh-flow/src/error.rs
- zenoh-flow/src/lib.rs
- zenoh-flow/src/model/dataflow.rs
- zenoh-flow/src/model/link.rs
- zenoh-flow/src/runtime/graph/link.rs
- zenoh-flow/src/runtime/graph/mod.rs
- zenoh-flow/src/runtime/resources.rs
- zenoh-flow/src/runtime/runners/mod.rs
- zenoh-flow/src/types.rs
This PR contains some internal as well as external refactoring:
- New link description
- Using references when possible
- Moved `ZFError` to the `error.rs` file
- Removed commented and unused code
> Refactoring

- zenoh-flow-examples/examples/camera-source.rs
- zenoh-flow-examples/examples/counter-source.rs
- zenoh-flow-examples/examples/example-buzz.rs
- zenoh-flow-examples/examples/example-fizz.rs
- zenoh-flow-examples/examples/face-detection.rs
- zenoh-flow-examples/examples/frame-concat.rs
- zenoh-flow-examples/examples/manual-source.rs
- zenoh-flow-examples/examples/object-detection-dnn.rs
- zenoh-flow-examples/examples/random-source.rs
- zenoh-flow-examples/examples/simple-pipeline.rs
- zenoh-flow-examples/examples/sum-and-send.rs
- zenoh-flow-examples/examples/video-file-source.rs
- zenoh-flow-examples/examples/video-pipeline.rs
- zenoh-flow/src/runtime/runners/operator.rs
- zenoh-flow/src/runtime/runners/source.rs
- zenoh-flow/src/traits.rs
- zenoh-flow/src/types.rs
Main benefit is that we remove 2 unneeded clones…!
> refacto: `output_rule` takes ownership

- zenoh-flow/src/runtime/dataflow/loader.rs
> Fix make_file_path to work with relative paths

- zenoh-flow/src/runtime/token.rs
> fix: impl std::fmt::Display for TokenAction

- zenoh-flow/src/runtime/token.rs
- zenoh-flow/src/types.rs
> adding #[derive(Clone)] for Tokens and DeadlineMiss

- cargo-zenoh-flow/src/bin/main.rs
- zenoh-flow-ctl/src/main.rs
- zenoh-flow-daemon/Cargo.toml
- zenoh-flow-daemon/src/daemon.rs
- zenoh-flow/Cargo.toml
- zenoh-flow/src/error.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/source.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_test.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/sink_e2e_deadline_tests.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/source_e2e_deadline_tests.rs
- zenoh-flow/src/runtime/mod.rs
- zenoh-flow/src/runtime/resources.rs
- zenoh-flow/tests/dataflow.rs
- zenoh-flow/tests/e2e_deadline.rs
- zenoh-flow/tests/input_rule_drop.rs
- zenoh-flow/tests/local_deadline.rs
> Updated to latest Zenoh API

- zenoh-flow/src/runtime/resources.rs
As discussed in #61 this PR contains the optimizations in the `resouces.rs` file.
The functions `get_vec_from_zenoh<T>` and `get_from_zenoh<T>` are reused along the `DataStore` to get data from zenoh. Both in the case of single data or vector of the same type.
The only function that cannot make use of it is `get_flow_instance_runtimes` as it gets `Vec<Uuid>` from the `KeyExpr` in zenoh.
> Code-reuse in resources.rs

- zenoh-flow-daemon/src/daemon.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/operator.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/source.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_e2e_deadline_tests.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/operator_test.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/sink_e2e_deadline_tests.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/tests/source_e2e_deadline_tests.rs
- zenoh-flow/src/types.rs
This PR fixes an `attempt to subtract with overflow` error in `daemon.rs`
It also removes a wild `unwrap()` in the same file.
> Fix in zenoh-flow-daemon

- .github/workflows/ci.yml
This PR is a better implementation of #70 
TODOs:
> Multi-OS and Multi-Platform CI

- cargo-zenoh-flow/Cargo.toml
- zenoh-flow-ctl/Cargo.toml
- zenoh-flow-daemon/Cargo.toml
- zenoh-flow-daemon/etc/zenoh.json
- zenoh-flow-derive/Cargo.toml
- zenoh-flow/Cargo.toml
> Prepare for 0.2.0

- zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
- zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
- zenoh-flow/src/runtime/resources.rs
This PR fixes the CI issues by using the new Zenoh Buffer APIs
> Update to new Zenoh's buffer API

- zenoh-flow-daemon/src/daemon.rs
This fixes: https://github.com/ZettaScaleLabs/zenoh-flow-python/issues/4
> Using new Zenoh config API

- zenoh-flow-daemon/etc/zenoh.json
> new zenoh config file

- cargo-zenoh-flow/Cargo.toml
- zenoh-flow-daemon/Cargo.toml
- zenoh-flow-derive/Cargo.toml
- zenoh-flow/Cargo.toml
- zfctl/Cargo.toml
> Bump to async-std 1.11

- zenoh-flow/src/runtime/resources.rs
> update match on zenoh sample encoding

- zenoh-flow/src/runtime/token.rs
> Added DataToken::new(action, data)

- zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
The previous behavior was as following:
1. create a barrier that requires 2 calls to be lifted,
2. make the node call the barrier (1st call) and block on this,
3. when the user calls `destroy`, the RunnerManager calls again the barrier (2nd
call) and effectively stops the node.
The issue was when a node fails (syntax error in Python for instance), the node
is restarted and steps 2. above is repeated. The barrier is then lifted, which
eventually stops the node.
Using channels solves that issue.
> fix: use channels instead of barriers to stop nodes

- .github/workflows/ci.yml
Upstream issue: https://github.com/actions/checkout/issues/760
> ci: fix to recent CVE on git prevents CI from properly executing

- .github/workflows/release.yml
> Adding almost empty release.yml

- README.md
> Add instructions to apt repository in README.md

- zenoh-flow-daemon/etc/runtime.yaml
> Fix wild slash in runtime.yml

- .github/workflows/nightly.yml
Initial nightly CI, to add the actions file in the master (so we can test the pipeline actually...).
Needs to be improved by a 2nd PR.
> Initial nightly CI

- .github/workflows/nightly.yml
> Adding alpine and fedora in nightly builds

- cargo-zenoh-flow/src/bin/main.rs
- cargo-zenoh-flow/src/error.rs
- cargo-zenoh-flow/src/templates.rs
- cargo-zenoh-flow/src/utils.rs
- zenoh-flow-daemon/src/bin/zenoh-flow-daemon.rs
- zenoh-flow-daemon/src/worker.rs
- zenoh-flow/build.rs
- zenoh-flow/src/model/descriptor/node/operator.rs
- zenoh-flow/tests/dataflow.rs
- zenoh-flow/tests/validator.rs
- zfctl/src/main.rs
Fix new clippy warnings, with `cargo clippy --fix` and a manual one.
> Fix clippy warnings.

- Cargo.lock
- Cargo.toml
- zfctl/Cargo.toml
- env_logger
- failure
- exitfailure
- prettytable-rs
Some of these dependencies have security vulnerabilities associated with them.
> security: remove unneeded dependencies

- Cargo.lock
- zenoh-flow-commons/Cargo.toml
- zenoh-flow-commons/src/utils.rs
The licence of `ramhorns` is incompatible with our project.
> fix(deps): replace `ramhorns` with `handlebars`

- Cargo.lock
- zenoh-flow-derive/Cargo.toml
- zenoh-flow-derive/src/lib.rs
This commit also rehabilitates the doctest -- as they should have stayed.
> doc(derive): improve documentation

- zenoh-flow-standalone-runtime/src/main.rs
Providing a Zenoh configuration allows, among other advantages, connecting to remote Zenoh networks.
* zenoh-flow-standalone-runtime/src/main.rs: add the '-z' option to provide the path to a Zenoh configuration.
> feat(standalone-runtime): allow providing a Zenoh configuration

- zenoh-flow-standalone-daemon/src/main.rs
With this change, users can specify, in a dedicated file, the configuration of the Zenoh-Flow Runtime as well as Zenoh's.
This allows setting the name and supported extensions in a dedicated file, passed via the '-c' option.
Similarly to other executable, the configuration for Zenoh can be passed via the '-z' option.
* zenoh-flow-standalone-daemon/src/main.rs:
- improve the documentation of the different command line options,
- make the 'name' option and 'configuration' mutually exclusive,
- handle the different options.
> feat(standalone-daemon): accept optional Zenoh/Zenoh-Flow configurations

- zenoh-flow-commons/src/configuration.rs
Users provide the configuration, it is then logical to let them own it and modify it.
In addition, the current status of the Python bindings leverages the configuration to pass certain required information.
* zenoh-flow-commons/src/configuration.rs:
- remove the `Arc` inside the `Configuration` structure,
- implement `DerefMut` for the `Configuration` facilitating mutation.
> refactor(commons): allow mutating and owning a `Configuration`

- zenoh-flow-standalone-daemon/src/main.rs
Although the option was present, the daemon did not actually read and process the configuration file.
This commit introduces this feature, which allows loading extensions and paves the way for nodes written in other programming languages.
* zenoh-flow-standalone-daemon/src/main.rs: read the configuration file pointed at by the provided path.
> feat(standalone-daemon): pass configuration with `-c` CLI option
